// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCireEnfOCuE0htL4GFnNN2XTJq0ufx-vY',
    appId: '1:344282095074:web:b7c03ca36892c848062dbb',
    messagingSenderId: '344282095074',
    projectId: 'quizapp-4024b',
    authDomain: 'quizapp-4024b.firebaseapp.com',
    storageBucket: 'quizapp-4024b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUbI8xE91pMkg1fNylCt2xoxXTaivR7g0',
    appId: '1:344282095074:android:aad74da945ef1287062dbb',
    messagingSenderId: '344282095074',
    projectId: 'quizapp-4024b',
    storageBucket: 'quizapp-4024b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwZwJ4roYbCm0kH976AJlhppvEk-FTFSw',
    appId: '1:344282095074:ios:4b1cd3c44908b12a062dbb',
    messagingSenderId: '344282095074',
    projectId: 'quizapp-4024b',
    storageBucket: 'quizapp-4024b.appspot.com',
    iosClientId: '344282095074-6je7po1n1grlfhe0n29hjm5nagnff0re.apps.googleusercontent.com',
    iosBundleId: 'com.paublo.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwZwJ4roYbCm0kH976AJlhppvEk-FTFSw',
    appId: '1:344282095074:ios:0c177421b842ba81062dbb',
    messagingSenderId: '344282095074',
    projectId: 'quizapp-4024b',
    storageBucket: 'quizapp-4024b.appspot.com',
    iosClientId: '344282095074-kda7v7tbmfum71jtd38icr1cg7obnjlf.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizapp',
  );
}
